language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - cd client && yarn test
  - cd client && yarn build
deploy:
  provider: surge
  skip_cleanup: true
  domain: dev-portal.surge.sh
  project: ./build/
on:
  branch: master