version: '3'
services:
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '3050:80'
    api:
        build:
            dockerfile: Dockerfile.dev
            context: /
        # volumes:
        #     - /app/node_modules
        #     - './app'
        environment:
            - PORT=5000
            - MONGO_URI=mongodb+srv://cowboysr0ck9:Password%2326@cluster0-vysbq.mongodb.net/test
            - SECRET=5E74697D136AF27CDC8F57E891A1E
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - './client:/app'
